name: rgbd-pointcloud
channels:
  - conda-forge
dependencies:
  - opencv
  - pip
  - pyrealsense2
  - pip:
    - sam-2 @ git+https://github.com/facebookresearch/segment-anything-2@c2ec8e14a185632b0a5d8b161928ceb50197eddc
    - gradio==5.0.2
    - litserve==0.2.3
    - open3d==0.19.0
    - open3d-python==0.3.0.0
    - pydantic==2.9.2
    - supervision==0.23.0
    - torch==2.4.1
    - torchnet==0.0.4
    - torchvision==0.19.1
    - transformers==4.44.2
    - uvloop==0.20.0
